export { default as HomePage } from './home/home';
export { default as ProfilePage } from './profile/profile';
export { default as TasksPage } from './Manager/VueConges';
export {default as Agenda} from './scheduler/scheduler';
export { default as FormDemande } from './Form/formDemande';
export {default as VueConges } from './ChefEquipe/VueConges';
export {default as VueCongesManager} from './Manager/VueConges';
export {default as Historique} from './Employe/Historique';
export {default as Statusm} from './Manager/statusm';
export {default as History} from './Manager/History';
export {default as MyHistory} from './ChefEquipe/myHistory';
