export const leaveTypes = [
    { id: 1, name: 'Annuel', nbjour :20,color: '#FF5733'},
    { id: 2, name: 'Maladie',nbjour :3,color: '#33FF57'  },
    { id: 3, name: 'Sans solde',color: '#3357FF' },
    { id: 4, name: 'Maternité',nbjour:30,color: '#FF33A1'},
    { id: 5, name: 'Paternité' ,nbjour :3,color: '#A1FF33'},
    { id: 6, name: 'Décès',color: '#F1FF32', subtypes: [
      { id: 61, name: 'Parent', nbjour: 5,color: '#BF00FF' },
      { id: 62, name: 'Grand parent', nbjour: 3,color: '#00BFFF' },
      { id: 63, name: 'Fils', nbjour: 5 ,color: '#00FFBF' },
      { id: 64, name: 'Oncle', nbjour: 2,color: '#FF00BF' }
    ]
  }
];
export const employees = [
  {
    name: 'John Heart',
    id: 1,
    color: '#56ca85',
    avatar: 'images/gym/coach-man.png',
    age: 27,
    department: 'Sales',
    fonction: 'Employe',
    managerId :3,
  },
  {
    name: 'Sandra Johnson',
    id: 2,
    color: '#ff9747',
    avatar: 'images/gym/coach-woman.png',
    age: 25,
    department: 'HR',
    fonction: 'Manager'
  },
  {
    name: 'Hanen',
    id: 3,
    color: '#ff9747',
    avatar: 'images/gym/coach-woman.png',
    age: 25,
    department: 'Sales',
    fonction: 'Employe'
  },
  {
    name: 'Mahdi',
    id: 4,
    color: '#ff9747',
    avatar: 'images/gym/coach-woman.png',
    age: 25,
    department: 'Sales',
    fonction: 'Employe'
  },
  {
    name: 'Firas',
    id: 6,
    color: '#ff9747',
    avatar: 'images/gym/coach-woman.png',
    age: 25,
    department: 'Sales',
    fonction: 'Chef'
  }
];
export const initialLeaves = [
  {
    nameemployee:'mahdi',
    id: 1,
    employeeID: 1,
    startDate: new Date('2023-06-01'),
    endDate: new Date('2023-06-05'),
    type: 'Annuel',
    subType:null,
    status: 'Approved',
    department: 'Sales',
    periodedebut:'matin',
    periodefin:'matin',
    explanation: 'mmm',
    attachment: null,
  },
  {
    nameemployee:'mahdi',
    id: 2,
    employeeID: 1,
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-06-03'),
    type: 'Décès',
    subType:'Oncle',
    status: 'Pending',
    department: 'Sales',
    periodedebut:'matin',
    periodefin:'matin',
    explanation: 'hh',
    attachment:'certif.txt'
  },
  {
    nameemployee:'hanen',
    id: 3,
    employeeID: 2,
    startDate: new Date('2023-07-05'),
    endDate: new Date('2023-07-06'),
    type: 'Maladie',
    status: 'Approved',
    department: 'HR',
    periodedebut:'matin',
    periodefin:'matin',
    explanation: 'null'
  },
  {
    nameemployee:'mahdi',
    id: 4,
    employeeID: 1,
    startDate: new Date('2023-08-12'),
    endDate: new Date('2023-08-15'),
    type: 'Annuel',
    subType:null,
    status: 'Pending',
    department: 'Sales',
    periodedebut:'Après-midi',
    periodefin:'matin',
    explanation: 'null',
    attachment: null,
  },
  {
    nameemployee:'mahdi',
    id: 5,
    employeeID: 1,
    startDate: new Date('2023-04-10'),
    endDate: new Date('2023-04-13'),
    type: 'Annuel',
    subType:null,
    status: 'Rejected',
    department: 'Sales',
    periodedebut:'matin',
    periodefin:'aprés midi',
    explanation: 'null',
    attachment: null,
  },
  {
    nameemployee:'mahdi',
    id: 6,
    employeeID: 1,
    startDate: new Date('2024-07-12'),
    endDate: new Date('2024-07-13'),
    type: 'Maladie',
    subType:null,
    status: 'Pending',
    department: 'Sales',
    periodedebut:'Après-midi',
    periodefin:'matin',
    explanation: 'null',
    attachment: null,
  },
];